[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "slack-bolt>=1.18.0",
    "GitPython>=3.1.0",
    "requests>=2.31.0",
    "websocket-client>=1.6.0",
    "flask>=3.1.1",
]
